---
title: "p8105_hw6_ew2717"
author: "Eric Wang"
output: github_document
---

```{r, echo = FALSE, message = FALSE}

library(tidyverse)
library(modelr)
library(ggcorrplot)
library(purrr)
library(rstatix)

set.seed(999)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "100%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1 

#### Loading and cleaning the data set

```{r}

birthweight_df <- 
  read_csv("data/birthweight.csv") %>%
  janitor::clean_names()

```

#### Checking for missing data

```{r}

skimr::skim(birthweight_df)$n_missing

```

As seen above, there are no missing values for any of the variables in this data set.

#### Finding rows and columns

```{r}

rows = birthweight_df %>% nrow()
columns = birthweight_df %>% ncol()

```

There are `r rows` rows and `r columns` columns in this data set. 

